### PR TITLE
Bugfix. Add javascript implementation

### PR DESCRIPTION
**Pull request by cybercase**
Hi Rasky :)

I've just ported to Javascript your python implementation of GCS.
If you want to give me a feedback or just accept the pull request it would be nice!

### CODE REVIEW

**Comment by rasky** [comment]
Hi Cyber, thanks for the submission! The Javascript implementation seems interesting, and provides for a good online demo.

Can you please split the fix for issue #1 in a separate pull request? I will review the rest soon.

Thanks!

**Comment by cybercase** [comment]
Ok, I've splitted the fix for Issue #1 into a separate pull request!

**Comment by arj03** [comment]
Interesting! The more implementations the better :)

**Comment by rasky** [comment]
@cybercase I've merged your code, but can you please provide a new pull request to clarify licensing? I would prefer the "unlicense" license, like the rest of my code.

**Comment by cybercase** [comment]
Yes, I also want to keep the "unlicense" license. I expected the same license was automatically used after merging my request into your repository. Do I have to provide the same license header for each of my files?

**Comment by rasky** [comment]
Yes please

**Pull request merged**
